### ISSUE TITLE
Название заголовка

### ISSUE THREAD

**Issue by tapochek666** [shash29exe/Weather-Notification-11#1]
Приветствую.Всё работает,но как убрать "Python" или прописать своё?
![Буфер обмена_08-28-2024_01](https://github.com/user-attachments/assets/5587f97b-6aea-4be7-8c46-bd0f0cd139ce)

**Comment by shash29exe** [comment]
Привет! Можно прописать атрибут app_id.
```
toast(app_id="App Name", title, f"{content} {result} °C", button='Закрыть')
```
Не уверен что работает, потом проверю.

**Comment by tapochek666** [comment]
Я пробовал такую строчку вставить-не получилось (
"app_id": "App Name",

**Comment by shash29exe** [comment]
Если нужно указывать через json, то вот:
```
def main():
    json_file_path = 'data.json'
    try:
        data = load_data_from_json(json_file_path)

        name = data['app_id']
        place = data['place']
        country = data['country']
        delay = int(data['delay'])
        title = data['title']
        content = data['content']
        unit_of_measurement = data['unit of measurement']
        api_key = data['api_key']
```

```
def show_weather_notification(name, place, country, title, content, unit_of_measurement, api_key):
    try:
        result = get_weather_data(place, country, unit_of_measurement, api_key)
        toast(app_id = name, title, f"{content} {result} °C", button='Закрыть')
    except Exception as e:
        print("Ошибка при показе уведомления о погоде:", e)
        raise
```

Ну как то так

**Comment by tapochek666** [comment]
Сразу не сказал...Я не програмист.Куда этот код вставить?В data.json?если
да,то программа с ошибками открывается (

ср, 28 авг. 2024 г. в 06:55, shash29 ***@***.***>:

**Comment by shash29exe** [comment]
data.json - это файл конфигурации.

Если вам нужно изменить заголовок уведомления через код, то вот:
```
from pyowm import OWM
from win11toast import toast
import time
import json
import pystray
import PIL.Image
import threading
import os
import webbrowser

def load_data_from_json(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        data = json.load(file)
    return data

def get_weather_data(place, country, unit_of_measurement, api_key):
    try:
        owm = OWM(api_key)
        mgr = owm.weather_manager()
        observation = mgr.weather_at_place(f"{place}, {country}")
        w = observation.weather
        temp = w.temperature(unit_of_measurement)['temp']
        result = str(round(temp))
        return result
    except Exception as e:
        print("Ошибка при получении данных о погоде:", e)
        raise

def show_weather_notification(place, country, title, content, unit_of_measurement, api_key):
    try:
        result = get_weather_data(place, country, unit_of_measurement, api_key)
        toast(app_id="App name"title, f"{content} {result} °C", button='Закрыть')
    except Exception as e:
        print("Ошибка при показе уведомления о погоде:", e)
        raise

def close(icon):
    print("Программа завершена")
    icon.stop()

def config():
    os.startfile('data.json')

def github_open():
    webbrowser.open_new_tab("https://github.com/shashzxc/Weather-Notification-11")

def weather_thread(place, country, title, content, unit_of_measurement, delay, api_key, icon):
    while True:
        try:
            show_weather_notification(place, country, title, content, unit_of_measurement, api_key)
            time.sleep(delay)
        except Exception as e:
            print("Общая ошибка:", e)
            toast(f'Общая ошибка: {str(e)}, Программа остановит работу', button='Закрыть')
            icon.stop()
            break

def main():
    json_file_path = 'data.json'
    try:
        data = load_data_from_json(json_file_path)

        place = data['place']
        country = data['country']
        delay = int(data['delay'])
        title = data['title']
        content = data['content']
        unit_of_measurement = data['unit of measurement']
        api_key = data['api_key']

        image = PIL.Image.open("icon.png")
        icon = pystray.Icon('Weather Notification 11', image, menu=pystray.Menu(
            pystray.MenuItem('Узнать погоду сейчас',
                             lambda: show_weather_notification(place, country, title, content,
                                                              unit_of_measurement, api_key)),
            pystray.MenuItem('Открыть конфиг-файл', config),
            pystray.MenuItem('Открыть проект на Github', github_open),
            pystray.MenuItem('Закрыть', close)
        ))

        t = threading.Thread(target=weather_thread,
                             args=(place, country, title, content, unit_of_measurement, delay, api_key, icon))
        t.daemon = True
        t.start()

        icon.run()
    except Exception as e:
        print("Общая ошибка:", e)
        raise

if __name__ == '__main__':
    main()
```

**Comment by tapochek666** [comment]
Так мне и надо через data.json.
Если я вставляю в него предпоследний код,то при запуске
Traceback (most recent call last):
  File "main.py", line 92, in <module>
  File "main.py", line 61, in main
  File "main.py", line 13, in load_data_from_json
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by shash29exe** [comment]
В data.json не нужно вставлять код. Он используется для конфигурации программы. Код должен быть в файле проекта - main.py

**Comment by tapochek666** [comment]
А потом его через  pyinstaller перегнать в exe,правильно?

ср, 28 авг. 2024 г. в 07:30, shash29 ***@***.***>:

**Comment by shash29exe** [comment]
Да, можно. Я через него и скомпилировал программу. Есть gui версия PyInstaller - auto-py-to-exe.

**Comment by tapochek666** [comment]
Благодарю.Можно закрыть тему.
